apiVersion: v1
kind: Service
metadata:
  name: superservice-service
spec:
  type: NodePort
  selector:
    app: superservice
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Optional, or let Kubernetes choose one