# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: superservice-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /time
# spec:
#   rules:
#   - host: superservice.local
#     http:
#       paths:
#       - path: /time
#         pathType: Prefix
#         backend:
#           service:
#             name: superservice-service
#             port:
#               number: 80
